version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: hanaroSpring
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: hanarodb
      MYSQL_USER: hanaro
      MYSQL_PASSWORD: 12345678
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
